### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by forty** [josephlr/tpm2-rs#1]
Hi! This project looks cool, I have been playing a bit with it, and I have a few questions:
1- is it dead / abandoned ? or waiting for contributions?
2- when trying out the read_pcrs example, it seems like I never get back more than 8 PCR (the 8 first that match the selection). I can change the selection and get different PCR (with different Hash Alg and/or PCR number), but never more than 8. Do you know if it could be a bug in the lib or just an TPM implementation specific behavior? (I'm on Linux)

Thanks!

**Comment by forty** [comment]
I found my answer for 2-: as per the spec, a TPML_DIGEST can contain a maximum of 8 digests, hence the limit on the response.

**Comment by josephlr** [comment]
Sorry for the late response. I haven't been working on this crate much. There's a new project at https://github.com/tpm-rs/tpm-rs with the goal of having Rust Libraries which are actually maintained by the TCG (the group which makes the TPM 2.0 spec). I'll archive this project and point people at the new project.

As for the `TPM2_PCR_Read`, you are correct. `TPML_Digest` has a hard cap of 8, so the response is capped at that.
